### ISSUE TITLE
Keep loading

### ISSUE THREAD

**Issue by benjaminbaldacci** [hi-jin/logseq-ask-pdf#5]
Hello, 
I configured the plugin this way but when I use it, it keeps loading. Do I do wrong?
Thanks

<img width="1680" alt="Capture d’écran 2024-11-11 à 01 27 20" src="https://github.com/user-attachments/assets/63a48a75-e286-4dbf-bc56-d8c5391c436e">

**Comment by hi-jin** [comment]
Thank you for your error report. I'll check soon!

Before that, did you wrote your API Key?

**Comment by hi-jin** [comment]
If you've entered your API key but it isn't working, press Command+Option+I to open DevTools and click on the Console tab to view the logs. Then, please try again and capture the full log.

**Comment by benjaminbaldacci** [comment]
Thanks for the Command+Options+I command, I found that the urls asked for embedings and LLM api should be https://api.openai.com/v1/ and not https://api.openai.com/v1/embeddings or https://api.openai.com/v1/chat/completions.
It works fine now!

**Comment by hi-jin** [comment]
Glad to hear that worked for you!

I meant to make it possible to specify host directly for using local models, 
but I found that can be more complex when using OpenAI models. (like you're experiencing!)
I'll make sure to fix that in the next version to make it easier for you.

*It's been a while since I've looked at this code because of my work, but I seem to recall that leaving host blank defaults to the OpenAI model. I'll make that more explicit :)
